In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                      index=['a', 'c', 'e'],
                      columns=['Ohio', 'Nevada'])
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [5]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                       index=['b', 'c', 'd', 'e'],
                      columns=['Missouri', 'Alabama'])
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [7]:
pd.merge(left2,right2,how ='outer',left_index = True,right_index = True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [8]:
left2.join(right2,how = 'outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [9]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                       index=['a', 'c', 'e', 'f'],
                      columns=['New York','Oregon'])
another

New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [13]:
left2.join([right2,another],how = 'outer')

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

In [14]:
left2.join([right2,another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

In [15]:
right2.join([left2,another])

Missouri  Alabama  Ohio  Nevada  New York  Oregon
b       7.0      8.0   NaN     NaN       NaN     NaN
c       9.0     10.0   3.0     4.0       9.0    10.0
d      11.0     12.0   NaN     NaN       NaN     NaN
e      13.0     14.0   5.0     6.0      11.0    12.0

In [16]:
another.join([left2,right2])
# join函数的index默认使用第一个，也就是join的主键的index

New York  Oregon  Ohio  Nevada  Missouri  Alabama
a       7.0     8.0   1.0     2.0       NaN      NaN
c       9.0    10.0   3.0     4.0       9.0     10.0
e      11.0    12.0   5.0     6.0      13.0     14.0
f      16.0    17.0   NaN     NaN       NaN      NaN

In [17]:
# 轴向连接
# 另一种数据合并运算也被称作连接（concatenation）、绑定（binding）或堆叠（stacking）。NumPy的concatenation函数可以用NumPy数组来做：

In [21]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.concatenate([arr,arr],axis = 0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
s1 = pd.Series([0,1],index= ['a','b'])
s1

a    0
b    1
dtype: int64

In [27]:
s2 = pd.Series([2,3,4],index= ['c','d','e'])
s2

c    2
d    3
e    4
dtype: int64

In [29]:
s3 = pd.Series([5,6],index= ['f','g'])
s3

f    5
g    6
dtype: int64

In [37]:
np.concatenate([s1,s2,s3],axis =1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [38]:
np.concatenate([s1,s2,s3],axis =0)

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [39]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [42]:
pd.concat([s1,s2,s3],axis = 1)
# 这种情况下，另外的轴上没有重叠，从索引的有序并集（外连接）上就可以看出来。传入join='inner'即可得到它们的交集：

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [43]:
s4 = pd.concat([s1,s3])

In [44]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [46]:
pd.concat([s4,s1])

a    0
b    1
f    5
g    6
a    0
b    1
dtype: int64

In [47]:
pd.concat([s4,s1],axis = 1)

0    1
a  0  0.0
b  1  1.0
f  5  NaN
g  6  NaN

In [48]:
pd.concat([s4,s1],axis = 1,join = 'inner')

0  1
a  0  0
b  1  1

In [52]:
# 通过join_axes指定要在其它轴上使用的索引：
pd.concat([s4,s1],axis = 1,join = 'outer',join_axes = [['a','d','e']])

0    1
a  0.0  0.0
d  NaN  NaN
e  NaN  NaN

In [56]:
pd.concat([s1,s4],keys = ['one','two'])

one  a    0
     b    1
two  a    0
     b    1
     f    5
     g    6
dtype: int64

In [60]:
result = pd.concat([s1,s4],keys = ['one','two','three'])
result

one  a    0
     b    1
two  a    0
     b    1
     f    5
     g    6
dtype: int64

In [61]:
result.unstack()

a    b    f    g
one  0.0  1.0  NaN  NaN
two  0.0  1.0  5.0  6.0

In [64]:
pd.concat([s1,s4],keys = ['one','two'],join = 'outer',axis =1)
# 如果沿着axis=1对Series进行合并，则keys就会成为DataFrame的列头：

one  two
a  0.0    0
b  1.0    1
f  NaN    5
g  NaN    6

In [65]:
pd.concat([s1,s4],keys = ['one','two'],join = 'outer'
         )

one  a    0
     b    1
two  a    0
     b    1
     f    5
     g    6
dtype: int64

In [66]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df1

one  two
a    0    1
b    2    3
c    4    5

In [68]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four'])
df2

three  four
a      5     6
c      7     8

In [75]:
pd.concat([df1,df2],join = 'outer',keys = ['ihio','titaly'],axis =1)

ihio     titaly     
   one two  three four
a    0   1    5.0  6.0
b    2   3    NaN  NaN
c    4   5    7.0  8.0

In [77]:
# 如果传入的不是列表而是一个字典，则字典的键就会被当做keys选项的值：
pd.concat({'level1':df1,'level2':df2},axis =1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [80]:
# 此外还有两个用于管理层次化索引创建方式的参数
# 举个例子，我们可以用names参数命名创建的轴级别：
pd.concat([df1,df2],axis = 1,keys = ['ohio','italy'],names = ['city','level'])

city  ohio     italy     
level  one two three four
a        0   1   5.0  6.0
b        2   3   NaN  NaN
c        4   5   7.0  8.0

In [83]:
# 最后一个关于DataFrame的问题是，DataFrame的行索引不包含任何相关数据：
# 在这种情况下，传入ignore_index=True即可：

In [85]:
df3 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df3

a         b         c         d
0  0.202524  0.111743  0.463085 -1.762749
1 -0.070760  0.116368 -0.620506 -0.368031
2 -0.175932 -0.777201 -0.773821 -0.573718

In [86]:
df4 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
df4

b         d         a
0  1.540773  0.764341  0.881464
1  1.551753  0.285492  1.065166

In [89]:
pd.concat([df3,df4],axis =1)

a         b         c         d         b         d         a
0  0.202524  0.111743  0.463085 -1.762749  1.540773  0.764341  0.881464
1 -0.070760  0.116368 -0.620506 -0.368031  1.551753  0.285492  1.065166
2 -0.175932 -0.777201 -0.773821 -0.573718       NaN       NaN       NaN

In [90]:
pd.concat([df3,df4],axis =1,ignore_index = True)

0         1         2         3         4         5         6
0  0.202524  0.111743  0.463085 -1.762749  1.540773  0.764341  0.881464
1 -0.070760  0.116368 -0.620506 -0.368031  1.551753  0.285492  1.065166
2 -0.175932 -0.777201 -0.773821 -0.573718       NaN       NaN       NaN

In [91]:
pd.concat([df3,df4],ignore_index = True)

a         b         c         d
0  0.202524  0.111743  0.463085 -1.762749
1 -0.070760  0.116368 -0.620506 -0.368031
2 -0.175932 -0.777201 -0.773821 -0.573718
3  0.881464  1.540773       NaN  0.764341
4  1.065166  1.551753       NaN  0.285492

In [92]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
              index=['f', 'e', 'd', 'c', 'b', 'a'])
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [93]:
 b = pd.Series(np.arange(len(a), dtype=np.float64),
               index=['f', 'e', 'd', 'c', 'b', 'a'])
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64

In [94]:
b[-1] = np.nan

In [95]:
np.where(pd.isnull(a),b,a)
#选择true的在x参数也就是这里的b显示，其他的显示a

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [96]:
pd.isnull(a)

f     True
e    False
d     True
c    False
b    False
a     True
dtype: bool

In [97]:
s = np.where(pd.isnull(b),b,a)
s = pd.Series(s)
s

0    NaN
1    2.5
2    NaN
3    3.5
4    4.5
5    NaN
dtype: float64

In [98]:
# 比如说，你可能有索引全部或部分重叠的两个数据集。
# Series有一个combine_first方法，实现的也是一样的功能，还带有pandas的数据对齐：
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [99]:
b[:-2]

f    0.0
e    1.0
d    2.0
c    3.0
dtype: float64

In [100]:
# 对于DataFrame，combine_first自然也会在列上做同样的事情，
# 因此你可以将其看做：用传递对象中的数据为调用对象的缺失数据“打补丁”：
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
                    'b': [np.nan, 2., np.nan, 6.],
                     'c': range(2, 18, 4)})
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [101]:
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
                    'b': [np.nan, 3., 4., 6., 8.]})
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [102]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [104]:
df2.combine_first(df1)

a    b     c
0  5.0  NaN   2.0
1  4.0  3.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN